# Load Data

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('df_cdc_joined_clean.csv')
df

/tmp/ipykernel_241248/3808358555.py:4: DtypeWarning: Columns (165,168) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_cdc_joined_clean.csv')

,Unnamed: 0,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ290,ALQ151,...,SMD057,SMQ078,SMD641,SMD650,SMD100FL,SMD100MN,SMQ670,SMQ621,SMD630,SMAQUEX2
0,0,109266.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,109271.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0
2,2,109271.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0
3,3,109271.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0
4,4,109273.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,1.0,30.0,15.0,1.0,1.0,1.0,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32957,32957,121170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32958,32958,121709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32959,32959,122778.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32960,32960,122879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32961,32961,123157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Rename Columns

In [8]:
column_mapping = {
    "DPQ010":"little_interest_in_doing_things",
    "DPQ020":"feeling_down_depressed_hopeless",
    "DPQ030":"trouble_falling_or_staying_asleep",
    "DPQ040":"feeling_tired_or_having_little_energy",
    "DPQ050":"poor_appetitie_or_overeating",
    "DPQ060":"feeling_bad_about_yourself",
    "DPQ070":"trouble_concentrating",
    "DPQ080":"moving_or_speaking_to_slowly_or_fast",
    "DPQ090":"thoughts_you_would_be_better_off_dead",
    "DPQ100":"difficult_doing_daytoday_tasks",
    "RXDRSC1":"ICD_10_CM_code1",
    "RXDRSC2":"ICD_10_CM_code2",
    "RXDRSC3":"ICD_10_CM_code3",
    "RXDRSD1":"ICD_10_CM_code1_desc",
    "RXDRSD2":"ICD_10_CM_code2_desc",
    "RXDRSD3":"ICD_10_CM_code3_desc"
}

In [7]:
df.rename(columns=column_mapping, inplace=True)
df

,Unnamed: 0,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ290,ALQ151,...,SMD057,SMQ078,SMD641,SMD650,SMD100FL,SMD100MN,SMQ670,SMQ621,SMD630,SMAQUEX2
0,0,109266.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,109271.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0
2,2,109271.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0
3,3,109271.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,2.0,30.0,20.0,NaN,NaN,1.0,NaN,NaN,1.0
4,4,109273.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,1.0,30.0,15.0,1.0,1.0,1.0,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32957,32957,121170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32958,32958,121709.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32959,32959,122778.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32960,32960,122879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32961,32961,123157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_trim = df[column_mapping.values()]

In [14]:
searchfor = ['F32','F33']

In [20]:
def has_depression_prescription(row):
    if df_trim['ICD_10_CM_code1'].str.contains('|'.join(searchfor)) == True:
        val = True
    elif df_trim['ICD_10_CM_code2'].str.contains('|'.join(searchfor)) == True:
        val = True
    elif df_trim['ICD_10_CM_code3'].str.contains('|'.join(searchfor)) == True:
        val = True   
    elif df_trim['ICD_10_CM_code1'].str.contains('|'.join(searchfor)) == True:
        val = True
    elif df_trim['ICD_10_CM_code2'].str.contains('|'.join(searchfor)) == True:
        val = True
    elif df_trim['ICD_10_CM_code3'].str.contains('|'.join(searchfor)) == True:
        val = True              
    else:
        val = -1
    return val


df_trim['ICD_10_CM_code1'].str.contains('|'.join(searchfor)) == True or /
df_trim['ICD_10_CM_code2'].str.contains('|'.join(searchfor)) == True or /
df_trim['ICD_10_CM_code3'].str.contains('|'.join(searchfor)) == True

SyntaxError: invalid syntax (2994454674.py, line 1)